sonar.projectKey=antoniobergas_hello-world
sonar.organization=antoniobergas

sonar.projectName=hello-world
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/hello-angular-azdo/lcov.info
sonar.typescript.lcov.reportPaths=coverage/hello-angular-azdo/lcov.info

sonar.sourceEncoding=UTF-8
